### PR TITLE
HEC-1057 upgrade library dependency

### PR DESCRIPTION
**Pull request by priyankadhiman3006**
library dependency changes

### CODE REVIEW

**Comment by AndyHWChung** [comment]
the build just failed, the unit tests passed but it came back with this:
```
[error] java.lang.NoClassDefFoundError: com/vladsch/flexmark/ast/Node
[error] 	at org.scalatest.tools.ReporterFactory.createHtmlReporter(ReporterFactory.scala:194)
```
that looks like some library clash, but we could give the build another go to see if it's just temporary

**Comment by AndyHWChung** [comment]
> the build just failed, the unit tests passed but it came back with this:
> 
> ```
> [error] java.lang.NoClassDefFoundError: com/vladsch/flexmark/ast/Node
> [error] 	at org.scalatest.tools.ReporterFactory.createHtmlReporter(ReporterFactory.scala:194)
> ```
> 
> that looks like some library clash, but we could give the build another go to see if it's just temporary

it looks like it's the `flexmark` thing which is causing it - I wonder if we really need it. Not sure what it does

**Comment by priyankadhiman3006** [comment]
this library is in other repos as well, but they didn't fail, let me have a double check

**Comment by priyankadhiman3006** [comment]
rebuild

**Review by AndyHWChung — APPROVED** [review]

**Review by meghana-viswanath — APPROVED** [review]

**Pull request merged**
